#!/bin/bash

echo "$IRODS_SERVICE_USER
$IRODS_SERVICE_GROUP
$IRODS_SERVICE_ROLE
$IRODS_ODBC_DRIVER_ENCODING
$DB_SERVER_HOST
$DB_SERVER_PORT
$DB_NAME
$DB_USERNAME
yes
$DB_PASSWORD
$DB_PASSWORD_SALT
$USE_LOCAL_STORAGE
$IRODS_DEFAULT_RESOURCE
$IRODS_VAULT_DIRECTORY
$IRODS_SERVER_ZONE_NAME
$IRODS_SERVER_PORT
$IRODS_PORT_RANGE_START
$IRODS_PORT_RANGE_END
$IRODS_CONTROL_PLANE_PORT
$IRODS_SCHEMA_VALIDATION_BASE_URI
$IRODS_SERVER_ADMIN_USERNAME
yes
$IRODS_SERVER_ZONE_KEY
$IRODS_SERVER_NEGOTIATION_KEY
$IRODS_CONTROL_PLANE_KEY
$IRODS_SERVER_ADMIN_PASSWORD
" | python3 /var/lib/irods/scripts/setup_irods.py
