#!/bin/bash

random-string() {
  env LC_CTYPE=C tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w ${1:-32} | head -n 1
}

create-random-password-if-empty() {
    if [[ -v $2 ]] || [[ -z $2 ]]; then
      echo $(random-string $1)
    else
      echo $2
    fi
}

export IRODS_SERVICE_USER=${IRODS_SERVICE_USER-"irods"}
export IRODS_SERVICE_GROUP=${IRODS_SERVICE_GROUP-"irods"}
export IRODS_SERVICE_ROLE=${IRODS_SERVICE_ROLE-"1"}
export IRODS_ODBC_DRIVER_ENCODING=${IRODS_ODBC_DRIVER_ENCODING-"1"}
export DB_SERVER_HOST=${DB_SERVER_HOST-"localhost"}
export DB_SERVER_PORT=${DB_SERVER_PORT-"5432"}
export DB_NAME=${DB_NAME-"icat"}
export DB_USERNAME=${DB_USERNAME-"irods"}
export DB_PASSWORD=$(create-random-password-if-empty 20 $DB_PASSWORD)
export DB_PASSWORD_SALT=$(create-random-password-if-empty 20 $DB_PASSWORD_SALT)
export USE_LOCAL_STORAGE=${USE_LOCAL_STORAGE-"yes"}
export IRODS_DEFAULT_RESOURCE=${IRODS_DEFAULT_RESOURCE-"demoResc"}
export IRODS_VAULT_DIRECTORY=${IRODS_VAULT_DIRECTORY-"/var/lib/irods/Vault"}
export IRODS_SERVER_ZONE_NAME=${IRODS_SERVER_ZONE_NAME-"tempZone"}
export IRODS_SERVER_PORT=${IRODS_SERVER_PORT-"1247"}
export IRODS_PORT_RANGE_START=${IRODS_PORT_RANGE_START-"20000"}
export IRODS_PORT_RANGE_END=${IRODS_PORT_RANGE_END-"20199"}
export IRODS_CONTROL_PLANE_PORT=${IRODS_CONTROL_PLANE_PORT-"1248"}
export IRODS_SCHEMA_VALIDATION_BASE_URI=${IRODS_SCHEMA_VALIDATION_BASE_URI-"file:///var/lib/irods/configuration_schemas"}
export IRODS_SERVER_ADMIN_USERNAME=${IRODS_SERVER_ADMIN_USERNAME-"rods"}
export IRODS_SERVER_ZONE_KEY=$(create-random-password-if-empty 32 $IRODS_SERVER_ZONE_KEY)
export IRODS_SERVER_NEGOTIATION_KEY=$(create-random-password-if-empty 32 $IRODS_SERVER_NEGOTIATION_KEY)
export IRODS_CONTROL_PLANE_KEY=$(create-random-password-if-empty 32 $IRODS_CONTROL_PLANE_KEY)
export IRODS_SERVER_ADMIN_PASSWORD=$(create-random-password-if-empty 20 $IRODS_SERVER_ADMIN_PASSWORD)
export VARIABLE_OUTPUT_DIR=${VARIABLE_OUTPUT_DIR-"/vagrant"}

echo "\
export IRODS_SERVICE_USER=$IRODS_SERVICE_USER
export IRODS_SERVICE_GROUP=$IRODS_SERVICE_GROUP
export IRODS_SERVICE_ROLE=$IRODS_SERVICE_ROLE
export IRODS_ODBC_DRIVER_ENCODING=$IRODS_ODBC_DRIVER_ENCODING
export DB_SERVER_HOST=$DB_SERVER_HOST
export DB_SERVER_PORT=$DB_SERVER_PORT
export DB_NAME=$DB_NAME
export DB_USERNAME=$DB_USERNAME
export DB_PASSWORD=$DB_PASSWORD
export DB_PASSWORD_SALT=$DB_PASSWORD_SALT
export USE_LOCAL_STORAGE=$USE_LOCAL_STORAGE
export IRODS_DEFAULT_RESOURCE=$IRODS_DEFAULT_RESOURCE
export IRODS_VAULT_DIRECTORY=$IRODS_VAULT_DIRECTORY
export IRODS_SERVER_ZONE_NAME=$IRODS_SERVER_ZONE_NAME
export IRODS_SERVER_PORT=$IRODS_SERVER_PORT
export IRODS_PORT_RANGE_START=$IRODS_PORT_RANGE_START
export IRODS_PORT_RANGE_END=$IRODS_PORT_RANGE_END
export IRODS_CONTROL_PLANE_PORT=$IRODS_CONTROL_PLANE_PORT
export IRODS_SCHEMA_VALIDATION_BASE_URI=$IRODS_SCHEMA_VALIDATION_BASE_URI
export IRODS_SERVER_ADMIN_USERNAME=$IRODS_SERVER_ADMIN_USERNAME
export IRODS_SERVER_ZONE_KEY=$IRODS_SERVER_ZONE_KEY
export IRODS_SERVER_NEGOTIATION_KEY=$IRODS_SERVER_NEGOTIATION_KEY
export IRODS_CONTROL_PLANE_KEY=$IRODS_CONTROL_PLANE_KEY
export IRODS_SERVER_ADMIN_PASSWORD=$IRODS_SERVER_ADMIN_PASSWORD
export VARIABLE_OUTPUT_DIR=$VARIABLE_OUTPUT_DIR
" > $VARIABLE_OUTPUT_DIR/active-irods-variables.sh
